version: '3.7'
services:
  api:
    build:
      context: ./
    volumes:
      - .:/app
    command: "node ./_server/api.js"
    ports:
      - 3000:3000
  image-downloader:
    build:
      context: ./
    volumes:
      - .:/app
    depends_on:
      - api
    environment:
      - DOCKER_ENVIRONMENT=true
    command: "sh -c 'sleep 10 && python3 download_images.py'"
  example-site:
    build:
      context: ./
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: "yarn start:docker"
    depends_on:
      - api
      - image-downloader
    ports:
      - 1313:1313
volumes:
  node_modules: